# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('concert_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('artist', models.CharField(max_length=50)),
                ('date_time', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('price_min', models.IntegerField()),
                ('price_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('venue', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=200)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='lfc_backend.Concert')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='lfc_backend.Concert')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='lfc_backend.Concert')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('concerts', models.ManyToManyField(related_name='tags', to='lfc_backend.Concert')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reported_concert', to='lfc_backend.User'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert_ratings', to='lfc_backend.User'),
        ),
        migrations.AlterUniqueTogether(
            name='concert',
            unique_together=set([('artist', 'date_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('venue', 'coordinates')]),
        ),
    ]
