# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConcertImage',
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
