# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 00:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0002_auto_20171225_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.URLField(default='http://www.w3.org/ns/anno.jsonld')),
                ('type', models.CharField(default='Annotation', max_length=255)),
                ('motivation', models.CharField(choices=[('ASSESSING', 'assessing'), ('BOOKMARKING', 'bookmarking'), ('CLASSIFYING', 'classifying'), ('COMMENTING', 'commenting'), ('DESCRIBING', 'describing'), ('EDITING', 'editing'), ('HIGHLIGHTING', 'highlighting'), ('IDENTIFYING', 'identifying'), ('LINKING', 'linking'), ('MODERATING', 'moderating'), ('QUESTIONING', 'questioning'), ('REPLYING', 'replying'), ('TAGGING', 'tagging')], max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('concert', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='lfc_backend.Concert')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEXT', 'text'), ('VIDEO', 'video'), ('AUDIO', 'audio'), ('IMAGE', 'image')], max_length=10)),
                ('format', models.CharField(choices=[('TEXT', (('PLAINTEXT', 'text/plain'),)), ('VIDEO', (('MPEGVIDEO', 'video/mpeg'), ('AVIVIDEO', 'video/avi'))), ('IMAGE', (('PNGIMAGE', 'image/png'), ('BMPIMAGE', 'image/bmp'), ('GIFIMAGE', 'image/gif'), ('JPEGIMAGE', 'image/jpeg'))), ('AUDIO', (('MIDIAUDIO', 'audio/midi'), ('MPEGAUDIO', 'audio/mpeg'))), ('unknown', 'Unknown')], max_length=15)),
                ('purpose', models.CharField(choices=[('ASSESSING', 'assessing'), ('BOOKMARKING', 'bookmarking'), ('CLASSIFYING', 'classifying'), ('COMMENTING', 'commenting'), ('DESCRIBING', 'describing'), ('EDITING', 'editing'), ('HIGHLIGHTING', 'highlighting'), ('IDENTIFYING', 'identifying'), ('LINKING', 'linking'), ('MODERATING', 'moderating'), ('QUESTIONING', 'questioning'), ('REPLYING', 'replying'), ('TAGGING', 'tagging')], max_length=20, null=True)),
                ('value', models.CharField(max_length=255)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='lfc_backend.Annotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnnotationTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEXT', 'text'), ('VIDEO', 'video'), ('AUDIO', 'audio'), ('IMAGE', 'image')], max_length=10)),
                ('format', models.CharField(choices=[('TEXT', (('PLAINTEXT', 'text/plain'),)), ('VIDEO', (('MPEGVIDEO', 'video/mpeg'), ('AVIVIDEO', 'video/avi'))), ('IMAGE', (('PNGIMAGE', 'image/png'), ('BMPIMAGE', 'image/bmp'), ('GIFIMAGE', 'image/gif'), ('JPEGIMAGE', 'image/jpeg'))), ('AUDIO', (('MIDIAUDIO', 'audio/midi'), ('MPEGAUDIO', 'audio/mpeg'))), ('unknown', 'Unknown')], max_length=15)),
                ('target_id', models.CharField(default='http://http://34.210.127.92:8000/concert/null/', max_length=255)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='lfc_backend.Annotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConcertReport',
            fields=[
                ('concert_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('ARTIST', 'artist'), ('DATE', 'date'), ('DESCRIPTION', 'description'), ('LOCATION', 'location'), ('TAG', 'tag'), ('MIN_PRICE', 'min_price'), ('MAX_PRICE', 'max_price'), ('SELLER_URL', 'seller_url'), ('IMAGE', 'image')], max_length=20, null=True)),
                ('suggestion', models.CharField(max_length=1000)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='lfc_backend.Concert')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='FragmentSelector', max_length=25)),
                ('conformsTo', models.CharField(choices=[('HTML', 'http://tools.ietf.org/rfc/rfc3236'), ('TEXT', 'http://tools.ietf.org/rfc/rfc5147'), ('MEDIA', 'http://www.w3.org/TR/media-frags/'), ('IMAGE', 'http://www.w3.org/TR/SVG/')], max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selector', to='lfc_backend.AnnotationTarget')),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('user_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=250)),
                ('reported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_user_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_user_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='concert_report',
            name='concert',
        ),
        migrations.RemoveField(
            model_name='concert_report',
            name='report_ptr',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='Concert_Report',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AlterUniqueTogether(
            name='userreport',
            unique_together=set([('reporter', 'reported')]),
        ),
    ]
