# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0002_auto_20171115_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='users',
            new_name='attendees',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='followed_users',
            field=models.ManyToManyField(related_name='following_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
