# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0002_auto_20171030_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='username',
        ),
    ]
