# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0003_auto_20171120_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='followed_users',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='followers',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
