# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0003_auto_20171028_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentId',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='concertId',
            new_name='concert_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='registeredUserId',
            new_name='owner_id',
        ),
    ]
