# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0003_auto_20171226_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='concert',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='upvotes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='annotationbody',
            name='annotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body', to='lfc_backend.Annotation'),
        ),
        migrations.AlterField(
            model_name='annotationbody',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('IMAGE', 'Image')], max_length=10),
        ),
        migrations.AlterField(
            model_name='annotationtarget',
            name='annotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='lfc_backend.Annotation'),
        ),
        migrations.AlterField(
            model_name='annotationtarget',
            name='target_id',
            field=models.CharField(default='http://http://34.210.127.92:8000/concert/null', max_length=255),
        ),
        migrations.AlterField(
            model_name='annotationtarget',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('IMAGE', 'Image')], max_length=10),
        ),
        migrations.AlterField(
            model_name='concertreport',
            name='concert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='lfc_backend.Concert'),
        ),
    ]
