# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0004_auto_20171028_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner_id',
        ),
    ]
