# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0004_auto_20171121_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='concert/%Y/%m/%d')),
            ],
        ),
    ]
