# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0004_auto_20171226_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertreport',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_concert_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='reliability_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='concertreport',
            name='report_type',
            field=models.CharField(choices=[('NAME', 'name'), ('ARTIST', 'artist'), ('DATE_TIME', 'date_time'), ('DESCRIPTION', 'description'), ('LOCATION', 'location'), ('MIN_PRICE', 'min_price'), ('MAX_PRICE', 'max_price'), ('SELLER_URL', 'seller_url'), ('IMAGE', 'image')], max_length=20),
        ),
        migrations.AlterField(
            model_name='concertreport',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concert_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='concertreport',
            unique_together=set([('reporter', 'concert', 'report_type', 'suggestion')]),
        ),
    ]
