# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0004_auto_20171030_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
