# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0005_auto_20171030_1703'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([]),
        ),
    ]
