# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0007_comment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='age',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='birth_date'),
        ),
    ]
