# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0008_auto_20171109_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='users',
            field=models.ManyToManyField(related_name='concerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
