# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0009_concert_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='artist_costumes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='concert_atmosphere',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='music_quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='stage_show',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='concert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='lfc_backend.Concert'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concert_ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
