# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0010_auto_20171112_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='artist_costumes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='concert_atmosphere',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='music_quality',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stage_show',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('owner', 'concert')]),
        ),
    ]
