# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0011_auto_20171112_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='concerts',
        ),
        migrations.AddField(
            model_name='concert',
            name='tags',
            field=models.ManyToManyField(related_name='concerts', to='lfc_backend.Tag'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth_date'),
        ),
    ]
