# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0012_auto_20171112_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='label',
        ),
        migrations.AddField(
            model_name='tag',
            name='context',
            field=models.CharField(default=datetime.datetime(2017, 11, 12, 20, 0, 29, 144104, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(default=datetime.datetime(2017, 11, 12, 20, 0, 41, 653708, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concert',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='concerts', to='lfc_backend.Tag'),
        ),
    ]
