# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lfc_backend', '0013_auto_20171112_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('spotify_id', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('url', models.URLField()),
                ('width', models.IntegerField()),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lfc_backend.Artist')),
            ],
        ),
        migrations.AlterField(
            model_name='concert',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='concerts', to='lfc_backend.Artist'),
        ),
    ]
