# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('artist', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('date', models.DateField(default=datetime.date.today)),
                ('minprice', models.IntegerField(default=0)),
                ('maxprice', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
