# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_auto_20170424_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='artist',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='concert',
            name='location',
            field=models.TextField(),
        ),
    ]
