# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_auto_20170424_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='location',
        ),
    ]
