# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 22:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0005_concert_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='artist',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(default=datetime.date(2017, 4, 24)),
        ),
        migrations.AlterField(
            model_name='concert',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
