# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0006_auto_20170424_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
