# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0007_auto_20170424_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('password', models.TextField(default='')),
                ('age', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
